FROM golang:alpine AS build
WORKDIR /app/bin
ADD . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build migrations/auto.go

FROM scratch 
WORKDIR /go/bin
COPY --from=build /app/bin/auto .
COPY --from=build /app/bin/.env .
ENTRYPOINT [ "./auto" ]
